import type { Metadata } from "next";
import { Geist, Geist_Mono, EB_Garamond } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AnnouncementBar from "@/components/AnnouncementBar";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const EB = EB_Garamond({
  variable: "--font-eb",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-giest-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${EB.variable} antialiased bg-amber-50`}>
        <main>
          <AnnouncementBar />

          {/* <Navbar /> */}

          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
